### ISSUE TITLE
(mongo-bundle) Add a `countRelation` type of fields

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#10]
**Is your feature request related to a problem? Please describe.**
It many cases, we want to count the number of related document without fetching them.

**Describe the solution you'd like**
This might be easy to integrate in the aggregation queries, though a question is raised : how do we filter the count ?
- counting local reference (like an array of foreign ids) is straightforward, but what if we want to count a filtered version of them ?
- counting distant referene that holds our local doc `_id` is not as straightforward as just getting the `$size` of a local array, but would always use the same method (lookup), making filtering easier.

**Comment by theodorDiaconu** [comment]
Documentation please, tests, and export it directly "createCountReducer" instead through ReducersToGo

**Comment by theodorDiaconu** [comment]
Documentation please, tests, and export it directly "createCountReducer" instead through ReducersToGo

**Comment by theodorDiaconu** [comment]
Doing some cleanups. This is achievable by hooking into the `pipeline` and using $size, an example exists in the docs.
