### ISSUE TITLE
`Validatable` behavior should take session into consideration, if any

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#100]

**Comment by theodorDiaconu** [comment]
It does now. While I love Validatable behavior I discourage its use because most of the times the model in your database is simple and you can easily use "validatable inputs" instead of resorting to such a barbaric way of doing validation.

**Comment by Fen747** [comment]
You are thinking of a software where data is mostly input-ed from a client view. In our case, we've got a big bunch of autonomous server work, webhooks, third party dependencies, etc. and we are therefore dealing with tthe DB a lot without going through GraphQL with sometimes quite sensitive data that we must ensure are properly valid at all time
