### ISSUE TITLE
useLiveData events not working

### ISSUE THREAD

**Issue by allocenx** [bluelibs/bluelibs#124]
**Describe the bug**
Basically I've been trying to use the useLiveData hook in order to get real-time records added into my list. My list's items also can be deleted and you can also add new items to the list, so by using that hook i wanted to show a toast with a specific message each time a record has added/edited or deleted, but they are not firing.

**To Reproduce**
1. Create a collection
2. Try to use the useLiveData hook with the 4th argument for the events
3. Add some console logs to each of those events
4. See that console logs will not appear since the events are not fired whenever you add/edit/delete a record

**Expected behavior**
I was expecting to see those events firing.

**Comment by theodorDiaconu** [comment]
Thank you, released
+ @bluelibs/x-ui-collections-bundle@1.0.3
