### ISSUE TITLE
`useData` from `x-ui-collections-bundle` to have `refetch()` capability.

### ISSUE THREAD

**Issue by allocenx** [bluelibs/bluelibs#125]
**Is your feature request related to a problem? Please describe.**
I was working on a simple todo-app list and was trying to use either the useData or useLiveData hook to get the newly added/removed items and while useLiveData hook was alright for this one, on the other hand useData hook, I found myself that I had to use the state to keep a copy of those items and work with that whenever i added or removed new items. 
It will be nice if useData can behave more or less like the hooks from react-query where also exports a refetch method to force reload it.

**Describe the solution you'd like**
Implement a way to refetch the new data on the useData hook.

**Describe alternatives you've considered**
Use useLiveData hook instead.

**Comment by theodorDiaconu** [comment]
Great idea!

**Comment by theodorDiaconu** [comment]
`useData` and `useDataOne` now export a refetch() function. released @bluelibs/x-ui-collections-bundle@1.1.0
