### ISSUE TITLE
Client-side `collection.findOneById()` does not return result when passed a string

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#147]
**Describe the bug**
When doing a `findOneById`  client side, it accepts a string as id, without me having to cast it as an `objectid` (just like it does when i updateOne), but I get no result. When I cast it as an `objectid`, it works though.

**Expected behavior**
As described in the doc / typings, both `string` and `ObjectId` should work, just like when passing an id to a `updateOne`

**Comment by theodorDiaconu** [comment]
This is how it should be. If you choose to work with _id as strings, this behavior can be bad.

**Comment by Fen747** [comment]
Yet the typings allows it, and I can pass a string successfully in `collection.updateOn`, which is not isomoprh
