### ISSUE TITLE
(question) Unsolicited Spam from "dan@bluelibs.org" about bluelibs

### ISSUE THREAD

**Issue by RaederDev** [bluelibs/bluelibs#153]
Hi.

I received unsolicited Spam via E-Mail about this project to my GitHub E-Mail address.
This is not only really annoying but a violation of Austria's law: §107 Telekommunikationsgesetz 2003 (TKG 2003). I don't want to receive any further advertisements for this library so please remove my Address from any of your databases.

As you seem to be based in Romania which is also a member of the EU I would strongly suggest you re-think your marketing strategy regarding this product given that similar laws exist across the EU.

Thank you.

**Comment by theodorDiaconu** [comment]
Hello @RaederDev 

The reason we contacted you was that we saw your GitHub Profile, your work on https://github.com/RaederDev/co-functional and others, and we considered you might be interested in giving us a little bit of feedback to improve the framework. You have decided to publicly expose your email, thus giving us the impression you would be ok to be contacted, I'm not sure there is any law that prevents anyone to contact someone else on their publicly exposed email on the internet asking questions and soliciting feedback.

You are not in any marketing list so we have nothing to remove you from, we do not send any follow-up emails, etc. We hand pick a select few that we think have a lot of skills and would be open to aid us in making this framework better. 

I hope this clarifies things, we wish you a nice day!

**Comment by RaederDev** [comment]
Alright, thank you for the response. I don't have any issues with anybody legitimately contacting me, it's just that the way the E-Mail was written gave off strong "let's just scrape random JS associated GitHub accounts and send them mails" vibes. 

Thank you for clarifying why you sent me that mail. No hard feelings, and I wish you the best for your project.
