### ISSUE TITLE
Nullable dates are parsed as 01/01/1970 instead of staying null when fetched from the GraphQL API

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#155]
**Describe the bug**
My document has a date field, non-required with a `null` default value. When fetched through the GQL API, I end up having a 01/01/1970 date instead of a null value.

**To Reproduce**
1. Create a blueprint collection with a nullable date
2. Insert an object in the collection with the date set as `null`
3. View/Edit the document from the generated CRUD on client side

**Expected behavior**
The parsed values shoudl detect the date is `null` and keep it that way instead of `new Date(null)`

**Comment by theodorDiaconu** [comment]
@Fen747 the response from GraphQL returns a timestamp, is that timestamp 0 in your network response?

In the serialise() we do run this check: https://github.com/bluelibs/bluelibs/blob/2a3c1daf228706b77682a92ca5f51edad70bf752/packages/x-bundle/src/graphql/scalars/Date.scalar.ts
