### ISSUE TITLE
`X.CheckDocumentExists` improvment

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#157]
**Is your feature request related to a problem? Please describe.**
When checking if a document exists, it often happens that we need it in the service, leading to a second `findOne` query on it, resulting in useless network and CPU usage.

**Describe the solution you'd like**
`X.CheckDocumentExists(Collection, (args) => args._id || null, { storeResult: { key: "myDocument", body: { ... } } }  )`

`storeResult` is an object or a boolean, defaulting to false.
When `storeResult === true`, `key = "chekedDocument"` and `body = { $all: true }`
When `storeResult` is an object, then both `key` and `body` are read or defaulted to the values as above.

**Describe alternatives you've considered**
Refecthing the document in my service

**Comment by theodorDiaconu** [comment]
I understand your concept, theoretically we can create a `findOrThrow()` kind of solution at collection level, this api feels a bit heavy

**Comment by theodorDiaconu** [comment]
I think this is custom behavior that will not be part of CheckDocumentExists, I think the solution is to create yourself a findOrThrow() at collection level.
