### ISSUE TITLE
Session expiration ate should support `null` to never expires

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#161]
In some cases, (bot users in mine) we would like the token to never automatically expire, meaning setting the `expiresAt` at `null`.

Currently, that wouldn't work as `expiresAt.getTime()` is called without checking the `expiresAt` type, which would simply throw an error.

**Comment by theodorDiaconu** [comment]
So, I had this situation right in the beginning how to treat falsy, missing expiresAts. And reading around the web and seeing what people think of session based implementations I made the choice to force expiresAt to be there. Please put it 1000 years into the future.
