### ISSUE TITLE
Blueprint - "isRequired: false" doesn't work in relations

### ISSUE THREAD

**Issue by qfl1ck32** [bluelibs/bluelibs#162]
Whenever you have a relation that is not required, Blueprint will still make it mandatory.

Example:

```
    relation({
      id: "endUser",
      to: "EndUsers",
      inversedBy: "owner",
      isRequired: false,
    }),
```

Result:

```
    endUser: EndUser!
```

**Comment by theodorDiaconu** [comment]
This might also be related to what @Fen747 has mentioned that we need to also split "requiredness" for API and Data Model too.
