### ISSUE TITLE
Thumbs.downloadUrl reducer is missing `path` in dependencies

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#167]
When fetching thumbs like so :
```typescript
thumbs: {
            id: 1,
            path: 1,
            downloadUrl: 1,
          },
```

It wokrs fine. But when fetching like this :

```typescript
thumbs: {
            id: 1,
            downloadUrl: 1,
          },
```

It throws with the following error : 
![Screen Shot 2022-01-31 at 17 50 17](https://user-images.githubusercontent.com/13072245/151836779-738be7f8-0602-432c-8726-f5cde385ae7c.png)

I guess the `path` is surely missing in the `downloadUrl` reducer.

**Comment by theodorDiaconu** [comment]
This was solved
