### ISSUE TITLE
[BLOCKER] When generating with a shared enum, it's not imported from the `api.types` files in `.base` file

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#172]
**Describe the bug**
I have a shared enum object user in a collection. When I generate then start the admin microservice, in the `MyCollectionEditForm.base.tsx` file, the enum initial value is correctly set to `initialValue: MyCollectionPossibleStatus.SOMETHING`, but `MyCollectionPossibleStatus` is not imported by default from the `api.types` file.

**Comment by theodorDiaconu** [comment]
@Fen747 please show me the code how the enum looks, how you've added it in blueprint, you've set a default value for it, but be careful, values that come from GraphQL are not always values you'd want. 

Maybe we should generate enum files for frontend as well?

**Comment by Fen747** [comment]
The enum in Blueprint :
```
export enum ClientRequestPossibleStatusesEnum {
  CLIENT_REQUEST = "CLIENT_REQUEST", // DEFAULT
  QUOTATION_TO_DO = "QUOTATION_TO_DO",
  QUOTATION_IN_PROGRESS_TECH = "QUOTATION_IN_PROGRESS_TECH",
  QUOTATION_DONE_TECH = "QUOTATION_DONE_TECH",
  QUOTATION_VALIDATED = "QUOTATION_VALIDATED",
  QUOTATION_TO_CORRECT_TECH = "QUOTATION_TO_CORRECT_TECH",
  QUOTATION_SENT = "QUOTATION_SENT",
  QUOTATION_SIGNED = "QUOTATION_SIGNED",
  PREPARATION = "PREPARATION",
  SITE = "SITE",
  BILLING_TO_DO = "BILLING_TO_DO",
  BILLING_CREATED = "BILLING_CREATED",
  BILLING_SENT = "BILLING_SENT",
  BILLING_TO_CORRECT = "BILLING_TO_CORRECT",
  BILLING_TO_BE_RELAUNCHED = "BILLING_TO_BE_RELAUNCHED",
  BILLING_PAID = "BILLING_PAID",
  BILLING_COMPLICATED = "BILLING_COMPLICATED",
  COMPLETED = "COMPLETED",
}

export const ClientRequestPossibleStatus = Studio.sharedModel({
  id: "ClientRequestPossibleStatus",
  description: "Client request status",
  enumValues: Object.values(ClientRequestPossibleStatusesEnum),
});

const application = app({
  id: "belett",
  sharedModels: [
    //  ...
    ClientRequestPossibleStatus,
  ],
```

The problem is that  after a generation, the type is correctly generated in `api.types.ts`, but is not imported in one of the `.base` file client side.

```
ERROR in src/bundles/UIAppBundle/pages/ClientRequestsManagement/config/ClientRequestEditForm.base.tsx:111:23
Cannot find name 'ClientRequestPossibleStatus'.
```

The fix is simply to import it manually / with the VSCode suggestion, from `api.root.ts`, but why ?

**Comment by Fen747** [comment]
This one starts to be very annoying, having to manually imports after each generation :P

**Comment by Fen747** [comment]
@theodorDiaconu Hi ! :)
Have you been able to reproduce maybe ? This is quite problematic as it forces us to manually fix a bunch of enums at each generation :/

**Comment by theodorDiaconu** [comment]
@y-moufakkr please prioritise this one as it's a blocker for David, thanks! @Fen747 we'll look into it ASAP

**Comment by y-moufakkr** [comment]
Hello @Fen747 , I ve tried to reproduce the bug but I couldn't, can you please share how you did you use the sharedModel enum `ClientRequestPossibleStatus`  in the collection `ClientRequest`?
also from what I m having right now, we are simply not importing the type from `api.types.ts` because we are not using it when generating the `.base` form code,
 PS: I m not 100% sure about this last statement thats why I asked to see how you using the sharedmodel
 if you are the one editing the` .base` code and need the type in it, thats another situation

**Comment by Fen747** [comment]
HI @y-moufakkr ,

I can assure you do use the enum in the file generation, as it is used to populate the options of the enum's selector, but it is not imported :) (liekly, the code writer service does not handle it).

Maybe the beste solution is to schedule a quick screen-share so I may make it clear easily for you :)

**Comment by y-moufakkr** [comment]
I am available right now, and tomorrow anytime, just hit me up in slack, in the meantime gonna try to reproduce the type import in the .base
