### ISSUE TITLE
Shared Object with `defaultValue = null` and `isRequired = false` are not `.nullable()`

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#173]
I have a shared `Address` type. In all my collections, the `address` field uses this shared model which is not `required` and has a `null` default value. However, when saving a document, I do get an error about the `null` value being incorrect and about setting the schema to `.nullable()` if it should be correct. Though when I look at the generated input, it looks like so :

```typescript
export class ProfileInsertInput {
  @Is(() => Schema.from(AddressInput))
  address?: AddressInput = null;

 // ...
}
```

Instead of :

```typescript
export class ProfileInsertInput {
  @Is(() => Schema.from(AddressInput).nullable())
  address?: AddressInput = null;

 // ...
}
```

**Comment by theodorDiaconu** [comment]
@qfl1ck32 can you look into this please?
