### ISSUE TITLE
Additional indexes are not added to the DB

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#175]
**Describe the bug**
In addition to the default ones and those from the behaviors, I've added a couple of indexes to my collection 👍 

```typescript
static indexes = [
    { key: { isDeleted: 1 } },
    { key: { createdAt: 1 } },
    { key: { createdBy: 1 } },
    { key: { email: 1 }, unique: true },
    { key: { phone: 1 }, unique: true },
  ];
```
However, and after restarting the server, those additional indexes are not added to the DB.
<img width="159" alt="Screen Shot 2022-02-01 at 16 42 45" src="https://user-images.githubusercontent.com/13072245/152000576-a28c8d8a-dfc4-4502-99a4-30bd2c5a5bb1.png">

**Comment by Fen747** [comment]
And now, for another collection, and even after several restarts, the indexes are never added ....

**Comment by theodorDiaconu** [comment]
Indexes take time to be created if it's a lot of data, but still it should be fast enough. It's also a matter of file inclusion, can you help me reproduce it?

**Comment by Fen747** [comment]
There's only 10 documents in my DB.
Though, after restarting the server, when I refresh my browser in a page that queries the collection where I've added the indexes, I now get the index creation error (because I added it myself on Atlas for testing purpose)

**Comment by Fen747** [comment]
Okay, I confirm : the indexes are added only when I query the collection ....

**Comment by Fen747** [comment]
Well, are we sure it comes from Mongo ?
If we take a look at Meteor, indexes are created immediatly at startup, which seems to be better to prevent any error when the app is running later.
