### ISSUE TITLE
Doc should be clear about `embody` usage

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#178]
```typescript
 body = secureBody(body, config);

  if (config.embody) {
    const getArguments = createGetArguments(body);
    config.embody.call(null, body, getArguments);
  }
```

The doc is not clear about the fact that, if we use `embody` to add some pipeline, it fully overrides the handling of the filters by Nova.

By the way, is it a good pattern ? Are we willing to fully override everytime ? In all 3 cases I add, I only wanted to `extend` the filters, not override them.

**Comment by theodorDiaconu** [comment]
Well, Nova doesn't know anything about the infrastructure, right, it works with REST APIs etc? Paste your full resolver, to see what options we've got. I'll close the issue because I currently see them very distinct (Args from graphql resolver <> nova embodyment and merging with arguments)
