### ISSUE TITLE
Allow removing optional related value

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#18]
**Describe the bug**
When editing a document that contains an optional relation to another collection, it is impossible to un-select a relation that would have been previously selected : the dropdown has no clear button or empty value option

**To Reproduce**
Create a collection with a relation to another one.

**Expected behavior**
If the relation is optional, we should be able to clear the value

**Comment by theodorDiaconu** [comment]
@bluelibs/x-ui-admin 1.4.8 released
