### ISSUE TITLE
useSmart- `Model is null` if kernel is not initialized

### ISSUE THREAD

**Issue by qfl1ck32** [bluelibs/bluelibs#191]
Basically, this is the error that appears when we try to use a smart (e.g. the guardian) before the kernel is initialized.

I know you are not supposed to do this, but I think we should handle the error, somehow.

![image](https://user-images.githubusercontent.com/56713436/152822326-dbb092c9-b83d-475e-9d5b-6502c8b1e9f1.png)

**Comment by theodorDiaconu** [comment]
Why would this happen?

**Comment by theodorDiaconu** [comment]
@qfl1ck32 the idea is that you shouldn't allow smart usage until the kernel is initialised? I would like to close it unless there's a reasonable situation where this might be used?
