### ISSUE TITLE
Windows 10 machine, issue creating new project

### ISSUE THREAD

**Issue by ConKuk** [bluelibs/bluelibs#198]
**Describe the bug**
When trying to create a new project using X we encounter the following issue.
X fails stating "The system cannot find the path specified." when running "cd BlueTest1; npm install"
Running it manually works, after that running "npm run blueprint:generate" works correctly as well.
But
Running "npm run start:api" throws again an error saying it cannot find the path, this time for "cd microservices;

Tested with node 14.17.0.
Tried that with Node 17.4.0, but that one has it's own problem that is related to node.
I'm not even sure the first one is related to this project, but hoping there is some way to fix that.

**To Reproduce**
Steps to reproduce the behavior on Node 14.17.0:
1. Run x to generate a new x:project.
2. You receive the first error.
3. run cd <projectname>; npm install manually
4. run "npm run blueprint:generate", wait for it to finish
5. Run "npm run start:api"
6. Receive the second error

**Expected behavior**
Should work as seen in the introduction video.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Additional context**
The strange thing is, the verbose log shows that the CWD is correct:

` verbose lifecycle BlueTest1@1.0.0~start:api: CWD: E:\a_study\BlueTest1`
`10 silly lifecycle BlueTest1@1.0.0~start:api: Args: [ '/d /s /c', 'cd microservices/api ; npm run start:dev' ]`

And yet it fails stating:

`The system cannot find the path specified.`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! BlueTest1@1.0.0 start:api: "cd microservices/api ; npm run start:dev"`
`npm ERR! Exit status 1`

And running "cd microservices/api ; npm run start:dev" shows me another issue.
"src/bundles/AppBundle/graphql/modules/Users/Users.resolvers.ts" seems to have been generated with the following imports.

`import { UserInsertInput, UserUpdateInput } from "......servicesinputs";`
`import { UsersCollection } from "......collectionsUsersUsers.collection";`

My main question after all of this is: Does this package work with Windows at all or should I used Linux.
On Linux there seems to be no issues.
If the answer is use Linux/Unix: Please add the requirements to work with Linux or Mac.
If it should work with windows as well, I think we need to find out what's going on.

P.S: 
Was tested on 2 independent machines.

**Comment by theodorDiaconu** [comment]
Thank you for submitting this issue. No, we do support Windows, this is very weird.

@y-moufakkr can you take a look?

**Comment by theodorDiaconu** [comment]
This should be fixed now :) Sorry for the delay!
