### ISSUE TITLE
Fix autoRefetch fields to support (or abort) when the update has a mongo modifier

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#213]
**Describe the bug**
The `autoRefetch fields` (based on update/insert input) I PR a few days ago only support `updateOne` being passed direct values, but will throw if we use a mongoModifier like `updateOne({ $set: { ...values } })`

We need to either abort autoRefecthing in this case or handle it.

1. If we abort the autoRefetch, it might introduce some weirdness to the developer who might expect autoRefetch to work OOTB in any case. We might want to ensure that the developer is warned about this usecase.
2. If we try to support mongo modifier syntax, how do we proceed ? It might be much more complex

**Comment by theodorDiaconu** [comment]
@Fen747 so currently updateOne is broken for EJSON modifiers?

**Comment by theodorDiaconu** [comment]
nvm, it was fixed
