### ISSUE TITLE
Expose colecction's `links`attribute

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#223]
**Is your feature request related to a problem? Please describe.**
In many cases (working with operator and deepsync in mine), it would be very useful to have the possibility to get the list of Links from a collection, like so :

```typescript
collection.getLinks()

// Would return comething like :
[{ field: "tags", isInversed: false, keyField: "tagIds", collection: TagsCollection }]
```

**Comment by theodorDiaconu** [comment]
collection.getStaticVariable("links");
