### ISSUE TITLE
`BeforeUpdateEvent` & `AfterUpdateEvent` are executed twice every time

### ISSUE THREAD

**Issue by OmarDahmen** [bluelibs/bluelibs#242]
**Describe the bug**
`BeforeUpdateEvent` & `AfterUpdateEvent` are executed twice every time.

**To Reproduce**
1. Go to any listener fiel under `microservices/api/src/bundles/AppBundle/listeners/`
2. Add this code : 
```
@On(BeforeUpdateEvent, {
    filter: (e: BeforeUpdateEvent) => {
      return true;
    },
  })
  before(e) {
    console.log("------- BEFORE ------");
  }

  @On(AfterUpdateEvent, {
    filter: (e: AfterUpdateEvent) => {
      return true;
    },
  })
  after(e) {
    console.log("------ AFTER -------");
  }
```
3. Make a change to any item of the object of the corresponding collection
4. See the console log, it looks like this :
```
------- BEFORE ------
------ BEFORE -------
------- AFTER ------
------ AFTER -------
```

**Expected behavior**
`BeforeUpdateEvent` & `AfterUpdateEvent`  should be executed once a time and console log should look like this : 
```
------- BEFORE ------
------ AFTER -------
```

**Comment by theodorDiaconu** [comment]
@OmarDahmen this might be due additional updates being made? show us either a reproduction either the call and which behaviors you have added. You can also console log the modifier to see exactly what's going on.

**Comment by Fen747** [comment]
@theodorDiaconu the code is unchanged, we simply send exactly `ONE` update from apollo-client (verified on the network panel), and let the default `toUpdateOne` executor perform its magic, and then we see the double logs.

**Comment by theodorDiaconu** [comment]
Can you print out the event data to see exactly what's getting update? That can help us identify what's going on.

**Comment by OmarDahmen** [comment]
@theodorDiaconu 
Printing `e.data` : 
```
------- BEFORE ------
e.data {
  filter: { _id: { '$in': [Array] }, isDeleted: { '$ne': true } },
  update: {
    '$set': ClientRequestUpdateInput {
      subjectId: new ObjectId("622a29ca863811f66aff64f5"),
      updatedAt: 2022-03-10T16:41:40.995Z,
      updatedById: new ObjectId("618a5965c692ed5ea2feacd1")
    }
  },
  fields: { all: [ 'subjectId' ], top: [ 'subjectId' ] },
  isMany: false,
  context: {
    userId: new ObjectId("618a5965c692ed5ea2feacd1"),
    [Symbol(LiveDataInfoTransfer)]: { documentIdsToUpdate: [Array] }
  },
  options: {
    context: {
      userId: new ObjectId("618a5965c692ed5ea2feacd1"),
      [Symbol(LiveDataInfoTransfer)]: [Object]
    }
  }
}
------- BEFORE ------
e.data {
  filter: { _id: { '$in': [Array] }, isDeleted: { '$ne': true } },
  update: {
    '$set': ClientRequestUpdateInput {
      subjectId: new ObjectId("622a29ca863811f66aff64f5"),
      updatedAt: 2022-03-10T16:41:40.995Z,
      updatedById: new ObjectId("618a5965c692ed5ea2feacd1")
    }
  },
  fields: { all: [ 'subjectId' ], top: [ 'subjectId' ] },
  isMany: false,
  context: {
    userId: new ObjectId("618a5965c692ed5ea2feacd1"),
    [Symbol(LiveDataInfoTransfer)]: { documentIdsToUpdate: [Array] }
  },
  options: {
    context: {
      userId: new ObjectId("618a5965c692ed5ea2feacd1"),
      [Symbol(LiveDataInfoTransfer)]: [Object]
    }
  }
}
------ AFTER -------
e.data {
  filter: { _id: { '$in': [Array] }, isDeleted: { '$ne': true } },
  update: {
    '$set': ClientRequestUpdateInput {
      subjectId: new ObjectId("622a29ca863811f66aff64f5"),
      updatedAt: 2022-03-10T16:41:40.995Z,
      updatedById: new ObjectId("618a5965c692ed5ea2feacd1")
    }
  },
  fields: { all: [ 'subjectId' ], top: [ 'subjectId' ] },
  context: {
    userId: new ObjectId("618a5965c692ed5ea2feacd1"),
    [Symbol(LiveDataInfoTransfer)]: { documentIdsToUpdate: [Array] }
  },
  isMany: false,
  result: {
    acknowledged: true,
    modifiedCount: 1,
    upsertedId: null,
    upsertedCount: 0,
    matchedCount: 1
  },
  options: {
    context: {
      userId: new ObjectId("618a5965c692ed5ea2feacd1"),
      [Symbol(LiveDataInfoTransfer)]: [Object]
    }
  }
}
------ AFTER -------
e.data {
  filter: { _id: { '$in': [Array] }, isDeleted: { '$ne': true } },
  update: {
    '$set': ClientRequestUpdateInput {
      subjectId: new ObjectId("622a29ca863811f66aff64f5"),
      updatedAt: 2022-03-10T16:41:40.995Z,
      updatedById: new ObjectId("618a5965c692ed5ea2feacd1")
    }
  },
  fields: { all: [ 'subjectId' ], top: [ 'subjectId' ] },
  context: {
    userId: new ObjectId("618a5965c692ed5ea2feacd1"),
    [Symbol(LiveDataInfoTransfer)]: { documentIdsToUpdate: [Array] }
  },
  isMany: false,
  result: {
    acknowledged: true,
    modifiedCount: 1,
    upsertedId: null,
    upsertedCount: 0,
    matchedCount: 1
  },
  options: {
    context: {
      userId: new ObjectId("618a5965c692ed5ea2feacd1"),
      [Symbol(LiveDataInfoTransfer)]: [Object]
    }
  }
}

```

**Comment by theodorDiaconu** [comment]
@OmarDahmen we cannot reproduce this, can you submit a quick repro project?

**Comment by OmarDahmen** [comment]
You could reproduce the bug on [this branch](https://gitlab.com/selfcity/belett-2/-/tree/feat/client-request-reference-naming) : `feat/client-request-reference-naming`
(@theodorDiaconu you have access granted)

Steps to reproduce : 
- Go to this file : ` /belett-2/microservices/api/src/bundles/AppBundle/listeners/ClientRequests.listener.ts` 
- Uncomment liens : 31-49
- Go to [http://localhost:8080/admin/subjects/](url)
- Create a subject
- Edit the subject and save
- You will have this output on your console : 
```
------- BEFORE ------
------- BEFORE ------
------ AFTER -------
------ AFTER -------
```

**Comment by y-moufakkr** [comment]
@OmarDahmen , can you give me access as well please ? thx u

**Comment by theodorDiaconu** [comment]
@OmarDahmen @y-moufakkr any news on this one? This shouldn't really happen. Unless the collection is initialised two times and the event listeners are attached two times.
So two possible reasons: either event is triggered twice, either we have the listener attached twice, you can modify EventManager.ts emit to log all events that get dispatched or setup a global listener.

**Comment by OmarDahmen** [comment]
@y-moufakkr You are right ! 
It's our fault :stuck_out_tongue_closed_eyes::sweat_smile:
It was nothing to do with bluelibs.
Sorry for the inconvenience, you could close the issue.
