### ISSUE TITLE
[TS] X-Bundle's "declare module" for IExecutionContext is not working

### ISSUE THREAD

**Issue by qfl1ck32** [bluelibs/bluelibs#243]
I expect that, when using collections, in `options` -> `context` I should have these options:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/56713436/157811491-5b0473b4-84c0-4365-9c2e-471932866a46.png">

where `live` would come from `X-Bundle`'s `defs.ts` file, in `src/behaviors/`:

At the moment, "live" is not showing up - just `userId` and `session`.

Am I missing something, though?

**Comment by theodorDiaconu** [comment]
@qfl1ck32 can you do something like import "@bluelibs/x-bundle"; on top of that file to ensure types are imported?

**Comment by theodorDiaconu** [comment]
@qfl1ck32 does this happen on a blueprint generated project?

**Comment by qfl1ck32** [comment]
I confirm it does still happen :)

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56713436/158758165-e8a4bfae-16ca-4572-bba8-65f158273730.png">

Also, importing @bluelibs/x-bundle won't work:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56713436/158758322-4aed9c57-fd71-4bf4-a3b9-b4a8e2d9a330.png">

**Comment by theodorDiaconu** [comment]
```
npm notice 
+ @bluelibs/x-bundle@1.2.3```
