### ISSUE TITLE
[useSubscription] - "_id"s are being retrieved as empty objects

### ISSUE THREAD

**Issue by qfl1ck32** [bluelibs/bluelibs#244]
In the subscription resolvers, the payload is sent well - the _ids are ObjectIds.

In `onAdded`, `onChanged`, ..., in `useSubscription(SUBSCRIPTION, { // here })`, the documents are received with `_id: {}`. Same goes for arrays of ids: `[{}, {}, ... {}]`

**Comment by theodorDiaconu** [comment]
This was related to latest fix in ejson.
