### ISSUE TITLE
[Bug] There is no resolver for ${collection}FindOneByID

### ISSUE THREAD

**Issue by qfl1ck32** [bluelibs/bluelibs#245]
We are creating a GQL query for this, but it doesn't have a resolver.

**Comment by theodorDiaconu** [comment]
This should use findOne behind the scenes, am I missing something?

**Comment by qfl1ck32** [comment]
I think yeah? This is the idea:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/56713436/158116225-256d5e7c-0e5b-471b-b710-f8104ccf3da3.png">


"UsersFindOneByID" doesn't have any kind of resolver attached to it (same goes for all the collections)

**Comment by qfl1ck32** [comment]
I think I explained the issue poorly. I am talking about the CRUD, not the collections. :)

**Comment by theodorDiaconu** [comment]
I understadn the issue, but why do we need it? Since we can use **FindOne({ _id })

**Comment by qfl1ck32** [comment]
Then we should at least remove the query (which is automatically generated), because it creates confusion :)

**Comment by theodorDiaconu** [comment]
Removed in v1.10.5 in x
