### ISSUE TITLE
[BLOCKER] [UICollectionBundle] `.deleteOne` doesn't work after a specific fetch

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#247]
**Describe the bug**
When opening my app, I can delete items without a problem.

There's one action though, that, when performed, prevents any further `collection.deleteOne` to work, and throws the following exception : 
```
apollo client Payload is not serializable: cyclic object value
```

In my case, the action that get things messy is to simply open a open that fetches a document to display it (actually that document was already in the apollo-cache, I just fetch some additional fields). here's the only query/Action performed between a working working deletion and a bugged one, that starts the problem  :

Query :
<img width="643" alt="Screen Shot 2022-03-14 at 16 50 16" src="https://user-images.githubusercontent.com/13072245/158209811-6af3c624-13d4-46b1-992d-08efc4589783.png">

Result :
<img width="717" alt="Screen Shot 2022-03-14 at 16 50 07" src="https://user-images.githubusercontent.com/13072245/158209821-a981175a-5872-4463-90df-cc4a28bfcad0.png">

After that, no more `.deleteOne` can be performed on any collection without throwing this : 

```
Error: Network request failed. Payload is not serializable: cyclic object value
    ApolloError index.js:29
    error QueryManager.js:137
    notifySubscription module.js:137
    onNotify module.js:176
    error module.js:229
    makeCallback asyncMap.js:32
    notifySubscription module.js:137
    onNotify module.js:176
    error module.js:229
    iterateObserversSafely iteration.js:4
    iterateObserversSafely iteration.js:4
    error Concast.js:36
    notifySubscription Observable.js:140
    onNotify Observable.js:179
    error Observable.js:240
    promise callback*setContext/</< bundle.esm.js:19
    Subscription Observable.js:197
    subscribe Observable.js:279
    complete Concast.js:57
    node_modules main.6c1597cc4e45fba49a4f.js:352551
    Concast Concast.js:75
    node_modules main.6c1597cc4e45fba49a4f.js:348647
    node_modules main.6c1597cc4e45fba49a4f.js:348174
    node_modules main.6c1597cc4e45fba49a4f.js:348173
    step tslib.es6.js:102
    verb tslib.es6.js:83
    __awaiter tslib.es6.js:76
    __awaiter tslib.es6.js:72
    node_modules main.6c1597cc4e45fba49a4f.js:348133
    node_modules main.6c1597cc4e45fba49a4f.js:346891
    deleteOne Collection.js:229
    onOk ContactCard.index.tsx:36
    onClick ActionButton.js:97
    handleClick button.js:209
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 22
    render confirm.js:89
    setTimeout handler*render confirm.js:78
    confirm confirm.js:129
    confirmFn index.js:29
    onDeleteContact ContactCard.index.tsx:18
    handleClick button.js:209
    React 5

```

I still can delete via a direct `apolloClient.mutate` though. So the bug is clearly inside the `.deleteOne` itself.

The code that works before I fetch the document, and throws after I did : 

```typescript
relatedContactsCollection
    .deleteOne(relatedContact._id)
    .catch(console.log);
```

**Comment by theodorDiaconu** [comment]
```apollo client Payload is not serializable: cyclic object value```

What is the object? Do you have certain serialisation options ?

**Comment by Fen747** [comment]
@theodorDiaconu I do not have the information about the exact object, the error is not really transparent. I'll try adding a error link on the apollo client

**Comment by theodorDiaconu** [comment]
@Fen747 do you happen to have documents that reference themselves directly or indirectly? Those cannot be JSON serialised? Looking at the code really, it's just a mutation.

**Comment by theodorDiaconu** [comment]
@Fen747 can you help me reproduce this?

**Comment by theodorDiaconu** [comment]
ping @Fen747
