### ISSUE TITLE
In reducer dependency object, either add support for `$` or remove it from the typings

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#253]
![Screen Shot 2022-03-25 at 17 01 06](https://user-images.githubusercontent.com/13072245/160157173-4e689a9d-b4bf-4c1e-b04f-d0719a25dfdf.png)

Here as you can see, the autocompletion from Typescript tells me I can specify some `$filters`. It would be so nice if that actually worked ! But unfortunately, it doesn't (when I log the `parent.followUps`, I always get all of the related item, irrespective of any filter or option I may have provided).

**Comment by theodorDiaconu** [comment]
Agreed. We need a non-optionable body graph configuration.
