### ISSUE TITLE
Fix caching doc

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#261]
The doc is broken here : https://www.bluelibs.com/docs/package-x-bundle/#caching

The caching params are in plain text
![Screen Shot 2022-04-08 at 12 00 52](https://user-images.githubusercontent.com/13072245/162413660-848665e3-f132-483c-9a7a-3b34cb77ad84.png)

**Comment by y-moufakkr** [comment]
Yeah saw that will fix it later

**Comment by theodorDiaconu** [comment]
Solved
