### ISSUE TITLE
Role-based access in the BP config

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#3]
**Is your feature request related to a problem? Please describe.**
After I created a new collection with a UI crud in blueprints, I have to customize the routes one by one to retrict the access to some roles.

**Describe the solution you'd like**
I'd expect the blueprint collections to support a `roles` key, that would be used to implement at generation time a simple role-based restriction on all the routes of the module by default. It could be overriden in the `ui` config like so :

```
ui: {
    label: "Tokens",
    list: {
        roles: fale // anyone can access the token list
    },
    edit: ,
    create: true,
    view: true,
    delete: true,
},
```

That would also allow to easily implement some basic role based control at API level

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by theodorDiaconu** [comment]
Repeated in https://github.com/bluelibs/bluelibs/issues/56
