### ISSUE TITLE
When you destructure useSmart, this is undefined in functions

### ISSUE THREAD

**Issue by CozmaCatalin** [bluelibs/bluelibs#304]
**Describe the bug**
In your components, if you destructure the object returned by `useSmart`, the function will not be able to acces `this`

**Expected behavior**
Work also when you destructure

**Screenshots**
**NO DESTRUCURE**
![Screenshot 2022-06-10 at 10 41 18](https://user-images.githubusercontent.com/44374252/173015863-8b65f0ee-de62-44d4-ad63-f3d135f1b464.png)
![Screenshot 2022-06-10 at 10 42 02](https://user-images.githubusercontent.com/44374252/173015923-c8096c15-1da7-4a96-b6eb-3a9a069213ab.png)

**WITH DESTRUCTURE**
![Screenshot 2022-06-10 at 10 43 11](https://user-images.githubusercontent.com/44374252/173016137-36cd5654-bd47-4133-9dbc-bc9c852cb45b.png)

![Screenshot 2022-06-10 at 10 42 59](https://user-images.githubusercontent.com/44374252/173016097-b11dca3f-247c-4c3a-b00e-736896fc1284.png)

**Comment by theodorDiaconu** [comment]
@CozmaCatalin this is normal behavior unfortunately, other way would be to write something like:
```
increment: () => {....}
```
