### ISSUE TITLE
Can you please not spam people with email about the library? (question)

### ISSUE THREAD

**Issue by Nikit-Singh** [bluelibs/bluelibs#305]
Please be ethical about how you try to grow the audience of this library instead of mailing random people from GitHub to test it.

**Comment by theodorDiaconu** [comment]
@Nikit-Singh I'm really sorry you feel this way, we pick GitHub profiles that we like and we want to get feedback from knowledgeable people, we loved your contributions to GitHub, interest in JS and other repositories. We are definitely not random in sending out an email, we apologise our email made you feel this way and gave you the impression we are unethical.
