### ISSUE TITLE
create  informative blueprint logs with an auto commit 

### ISSUE THREAD

**Issue by y-moufakkr** [bluelibs/bluelibs#306]
after each `blueprint:generate`  we add the changes to the logs and we commit so the generated files wont be in our next commit, which makes the code review easier

**Comment by Fen747** [comment]
Yes, yes and yes.

**Comment by theodorDiaconu** [comment]
I understand but what would for example prevent in doing a new script called:
```
"commit": "git commit -m 'Blueprint Generated Content'";
"blueprint:generate": "ts-node ... && npm run commit"
```

Something like this can ease your workflow and you have the sheer flexibility of doing whatever you want.
