### ISSUE TITLE
how to extend the IQueryContext and use it with the the mongo db clientSession in mongo-bundle,nova

### ISSUE THREAD

**Issue by y-moufakkr** [bluelibs/bluelibs#320]
I need to pass some params in "session" so I can use them in reducers, without passing the value in projection level, bcs I m gonna need that value in multi level reducers, "language for example"
I followed the docs to extend the `IQueryContext `in nova but it seems that its still a blocker for me,
 not only that, the `Mongodb.ClientSession` need to be changed as well bcs it doesn't accepts other fields, which force using the `query(collection,...) from nova` and not `Collection.query() from mongo-bundle`,
 
 Ps: in a separate branch I made an extra optional input `params?: { [key: string]: any }` for query in nova and in mongo-bundle , which gonna make things works  but is that acceptable ? 
for the record I m trying to pass language and country in session, so all the relations/reducers in the query  can have that specific country and language

**Comment by theodorDiaconu** [comment]
I think this was solved long ago.
