### ISSUE TITLE
[MongoBundle][MigrationsService] Migration service runs incorrect migrtions when migrating to lower version

### ISSUE THREAD

**Issue by iulianandrei** [bluelibs/bluelibs#321]
**Describe the bug**
The migration service of the mongo bundle has incorrect offset on down migrations: it skips the down migration for the current version and also runs the down migration of the target version.

For example, if the current version is 3 and we run `migrationService.migrateTo(1)`, the down methods of version 2 and version 1 are run, when it should actually run the down methods of versions 3 and 2.

**To Reproduce**
Steps:
1. Add X migration configs, with the versions being `[1, 2, ..., X]`.
2. Migrate to latest.
3. Migrate to some Y version, where `1 <= Y < X`,  using the `migrateTo` method.

**Expected behavior**
The "down" methods of migration steps `[X, X-1, ..., Y+1]` are run.

**Actual behavior**
The "down" methods of migration steps `[X-1, X-2, ..., Y]` are run.

**Comment by theodorDiaconu** [comment]
Solved via mongo-bundle@1.7.1
