### ISSUE TITLE
S3 Uploads doesn't recognize .env values 

### ISSUE THREAD

**Issue by tkamsker** [bluelibs/bluelibs#329]
**Describe the bug**
in bluelibs collections  have an file like FileLibs.ts 

import { collection, field, relation, shortcuts } from "../utils";
// import { Adhesion } from "./sharedEnums/Adhesion";
// import { Speed } from "./sharedEnums/Speed";
// import { Support } from "./sharedEnums/Support";
//import { PrinterState } from "./sharedEnums/PrinterState";

// import { MediaTypes } from "./sharedEnums/MediaTypes";
// import { I18NField } from "./sharedEnums/Translations";

export const Filelibrary = collection({
  id: "Filelibrary",
  representedBy: "name",
  behaviors: {
    blameable: true,
    softdeletable: true,
    timestampable: true,
  },

  mock: {
    count: 5,
  },

 //  representedBy: "translatedName",

  fields: [
    field.string("name", {
      isRequired: true,
    }),
    field({
      id: "technicalName",
      type: field.types.STRING,
    }),
    /*
    field({
      id: "speed",
      type: field.types.ENUM,
      model: () => Speed,
    }),
    field({
      id: "support",
      type: field.types.ENUM,
      model: () => Support ,
    }),
    field({
      id: "adhesion",
      type: field.types.ENUM,
      model: () => Adhesion,
    }),
    */
    field({
      id: "infill",
      type: field.types.INTEGER,
    }),
    field({
      id: "time",
      type: field.types.FLOAT,
    }),
    field({
      id: "machine_depth",
      type: field.types.INTEGER,
    }),
    field({
      id: "machine_width",
      type: field.types.INTEGER,
    }),
    field.object("filterinfo", {
      isArray: true,
      subfields: [
        field.string("ownerName"),
      ],
    }),  
    field({
      id: "toolhead",
      type: field.types.INTEGER,
    }),
    field.string("modelStatus"),
    field.string("status"),
    field.boolean("selected"),

    ...shortcuts.fields.blameable(),
    ...shortcuts.fields.timestampable(),
  ],

  relations: [
    shortcuts.relation.file("modelFile", { isRequired: false }),
/*    relation({
      id: "modelFile",
      to: "AppFiles",
      isMany: false, // you can also have multiple uploads
/*      field: s.field({
        id: `${id}Id`,
        type: s.field.types.OBJECT_ID,
        
      }),
      
      ui: {
        create: true,
        edit: true,
        list: true,
        listFilters: false,
        view: true,
      },
//      ...override,
    }),
*/
    shortcuts.relation.file("gFileUrl", { isRequired: false }),

/*    relation({
      id: "materialtype",
      to: "MaterialType",
    }),
    relation({
      id: "printertype",
      to: "PrinterType",
    }),
    relation({
      id: "colortype",
      to: "ColorType",
    }),
    */
/*    shortcuts.relation.user({
      id: "owner",
      unique: true,
    }),
    */
    ...shortcuts.relations.blameable(),
  ],
});

**To Reproduce**
1. Have the file Filelibs in collection 
2. npm i 
3. npm run blueprint:generate
5. set mongo and S3 Values in .env
6. npm run start:api  
7. npm run start:admin 
8. login and ry upload 

**Expected behavior**
File gets uploaded to S3 Bucket 

**Screenshots**
 error  {
    "message": "The AWS Access Key Id you provided does not exist in our records.",
    "locations": [
        {
            "line": 2,
            "column": 3
        }
    ],
    "path": [
        "AppFileUpload"
    ],
    "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
            "message": "The AWS Access Key Id you provided does not exist in our records.",
            "code": "InvalidAccessKeyId",
            "region": null,
            "time": "2023-02-23T07:48:42.127Z",
            "requestId": "PCF0R35RC0J9Y8S7",
            "extendedRequestId": "vv8lLSfhFGrpUTLQ53empkOSneLepTWwX4d+V/XvkE5wExtY27XjLDqa9gDHI6dvXmAZcExKVV0=",
            "statusCode": 403,
            "retryable": false,
            "retryDelay": 53.22251742300297,
            "stacktrace": [
                "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.",
                "    at Request.extractError (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/services/s3.js:711:35)",
                "    at Request.callListeners (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
                "    at Request.emit (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
                "    at Request.emit (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:686:14)",
                "    at Request.transition (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:22:10)",
                "    at AcceptorStateMachine.runTo (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/state_machine.js:14:12)",
                "    at /Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/state_machine.js:26:10",
                "    at Request.<anonymous> (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:38:9)",
                "    at Request.<anonymous> (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:688:12)",
                "    at Request.callListeners (/Users/thomaskamsker/Documents/Atom/Newmake3d/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
            ]

**Desktop (please complete the following information):**
 - OS: Linux ,OSX Node 18, 

**Additional context**
It seems that application is using mongo url from .env but not AWS S3 Parameters aka forgets them

**Comment by theodorDiaconu** [comment]
Can you show me your .env file , and your kernel.ts file @tkamsker ?

**Comment by tkamsker** [comment]
hi thank you her eis .env of microservices/api  and microservices/api/startup here the .env file (i changed the values of S3) APP_URL="http://localhost:3000"
ROOT_URL="http://localhost:4000"
ROOT_PORT=4000
MONGO_URL="mongodb://localhost:27017/test123"
AWS_ACCESS_KEY_ID=yyy
AWS_SECRET_ACCESS_KEY=zzz
AWS_BUCKET=yyy
[kernel.ts.zip](https://github.com/bluelibs/bluelibs/files/10838404/kernel.ts.zip)

AWS_REGION=eu-west-1
AWS_ENDPOINT=xxx
and the kernel as zip file thank you

**Comment by theodorDiaconu** [comment]
Can you log the secrets you get when you are in the kernel.ts file? Just
log the env ? Maybe you don't load the right .env variable somehow.

**Comment by tkamsker** [comment]
Hi i started api from vscode terminal to debug it ,.. and that is why i wrote the ticket it seems that the new x (compared to version in summer ) is "forgetting" the values 
so here is the log file 
thomaskamsker@ThomasAir-9 neumake3d % cd microservices/api 
thomaskamsker@ThomasAir-9 api % npm run start:dev
Debugger listening on ws://127.0.0.1:59981/17d3130d-dcae-456f-837a-c524aba58148
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> api@1.0.0 start:dev
> tsnd --respawn -r tsconfig-paths/register src/startup/index.ts

Debugger listening on ws://127.0.0.1:59983/557c6bc4-1d14-4d87-b472-152a1ba30a5d
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[INFO] 11:42:16 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
Debugger listening on ws://127.0.0.1:59985/112f4b99-ee9c-44d3-90b6-f4ec8312fdf4
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
---kernel

xxxxxxx      xxxxxxx
 x:::::x    x:::::x 
  x:::::x  x:::::x  
   x:::::xx:::::x   
    x::::::::::x    
     x::::::::x     X-Framework Server by BlueLibs
     x::::::::x     You are in control.
    x::::::::::x    
   x:::::xx:::::x   
  x:::::x  x:::::x  
 x:::::x    x:::::x 
xxxxxxx      xxxxxxx 

 info  Connecting to MongoDB database...
(node:95791) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
 info  Connected to the database.
(node:95791) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead 
 info  HTTP Server listening on port: 4000
 info  GraphQL endpoint ready: http://localhost:4000/graphql
Running app fixtures.
Added fixtures for colorType
Added fixtures for filelibrary
Added fixtures for material
Added fixtures for materialType
Added fixtures for printerType
Added fixtures for printer
Added fixtures for users
Created new login user-0@bluelibs.com:bluelibs
Created new login user-1@bluelibs.com:bluelibs
Created new login user-2@bluelibs.com:bluelibs
Created new login user-3@bluelibs.com:bluelibs
Created new login user-4@bluelibs.com:bluelibs
Created new login user-5@bluelibs.com:bluelibs
Created new login user-6@bluelibs.com:bluelibs
Created new login user-7@bluelibs.com:bluelibs
Created new login user-8@bluelibs.com:bluelibs
Created new login user-9@bluelibs.com:bluelibs
Completed app fixtures.
^CWaiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

thomaskamsker@ThomasAir-9 api % npm run start:dev
Debugger listening on ws://127.0.0.1:60029/ed445a33-70c0-4f9f-9140-102b12cd1114
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> api@1.0.0 start:dev
> tsnd --respawn -r tsconfig-paths/register src/startup/index.ts

Debugger listening on ws://127.0.0.1:60031/449ea167-be71-499e-b9a4-41ff89d797f7
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[INFO] 11:45:08 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
Debugger listening on ws://127.0.0.1:60033/9afeb730-ef9a-4b95-8800-8b771e407862
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
---kernel
{
  APP_URL: 'http://localhost:3000',
  ROOT_URL: 'http://localhost:4000',
  ROOT_PORT: 4000,
  MONGO_URL: 'mongodb://localhost:27017/test123',
  CONTEXT: 'development',
  AWS_ACCESS_KEY_ID: 'EXOee841d69b42d8902716276e1',
  AWS_SECRET_ACCESS_KEY: 'QGqvWsXhbtu6unLWugKy4MgFLhhrxpbO_nM2Ky7UCzQ',
  AWS_BUCKET: 'dev-neumake3d',
  AWS_REGION: 'eu-west-1',
  AWS_ENDPOINT: 'https://sos-at-vie-1.exo.io'
}
[class XS3Bundle extends Bundle]

xxxxxxx      xxxxxxx
 x:::::x    x:::::x 
  x:::::x  x:::::x  
   x:::::xx:::::x   
    x::::::::::x    
     x::::::::x     X-Framework Server by BlueLibs
     x::::::::x     You are in control.
    x::::::::::x    
   x:::::xx:::::x   
  x:::::x  x:::::x  
 x:::::x    x:::::x 
xxxxxxx      xxxxxxx 

 info  Connecting to MongoDB database...
(node:96153) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
 info  Connected to the database.
(node:96153) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead 
 info  HTTP Server listening on port: 4000
 info  GraphQL endpoint ready: http://localhost:4000/graphql
 error  Error was found when creating context: 
Context:  ApolloInvalidTokenException: (INVALID_TOKEN) Invalid token
    at contextReducers (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/@bluelibs/apollo-security-bundle/src/ApolloSecurityBundle.ts:101:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ApolloBundle.applyContextReducers (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/@bluelibs/apollo-bundle/src/ApolloBundle.ts:343:19)
    at ApolloServer.contextHandler [as context] (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/@bluelibs/apollo-bundle/src/ApolloBundle.ts:293:14)
    at ApolloServer.graphQLServerOptions (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/apollo-server-core/src/ApolloServer.ts:947:13)
    at resolveGraphqlOptions (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/apollo-server-core/src/graphqlOptions.ts:95:12)
    at runHttpQuery (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/apollo-server-core/src/runHttpQuery.ts:217:15) {
  data: {
    token: 'FBiWfPuepNJ9UsYYMFZoOAGaBLw4RshsgPTkNkOTCYNJEqB1qr9XhSUaM9wPNV4Z'
  }
}
 error  {
    "message": "Context creation failed: (INVALID_TOKEN) Invalid token",
    "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
            "stacktrace": [
                "ApolloInvalidTokenException: (INVALID_TOKEN) Invalid token",
                "    at contextReducers (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/@bluelibs/apollo-security-bundle/src/ApolloSecurityBundle.ts:101:19)",
                "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
                "    at ApolloBundle.applyContextReducers (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/@bluelibs/apollo-bundle/src/ApolloBundle.ts:343:19)",
                "    at ApolloServer.contextHandler [as context] (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/@bluelibs/apollo-bundle/src/ApolloBundle.ts:293:14)",
                "    at ApolloServer.graphQLServerOptions (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/apollo-server-core/src/ApolloServer.ts:947:13)",
                "    at resolveGraphqlOptions (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/apollo-server-core/src/graphqlOptions.ts:95:12)",
                "    at runHttpQuery (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/apollo-server-core/src/runHttpQuery.ts:217:15)"
            ]
        }
    }
}
 error  {
    "message": "The AWS Access Key Id you provided does not exist in our records.",
    "locations": [
        {
            "line": 2,
            "column": 3
        }
    ],
    "path": [
        "AppFileUpload"
    ],
    "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
            "message": "The AWS Access Key Id you provided does not exist in our records.",
            "code": "InvalidAccessKeyId",
            "region": null,
            "time": "2023-02-27T10:48:19.238Z",
            "requestId": "AGA0EJ08MSEEBN6Q",
            "extendedRequestId": "FdQPwwkOs0Whwx6v7igdesMvxmDbZGAb0M3LWWjAX0so5yRniWWn47jHaVYay/clKAsy5Ju83tI=",
            "statusCode": 403,
            "retryable": false,
            "retryDelay": 69.73436988147913,
            "stacktrace": [
                "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.",
                "    at Request.extractError (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/services/s3.js:711:35)",
                "    at Request.callListeners (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
                "    at Request.emit (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
                "    at Request.emit (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:686:14)",
                "    at Request.transition (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:22:10)",
                "    at AcceptorStateMachine.runTo (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/state_machine.js:14:12)",
thomaskamsker@ThomasAir-9 api % 
thomaskamsker@ThomasAir-9 api % 
thomaskamsker@ThomasAir-9 api % 
thomaskamsker@ThomasAir-9 api % npm run start:dev
Debugger listening on ws://127.0.0.1:60156/76738cd7-3b41-48a1-b82a-e4b933f4405f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> api@1.0.0 start:dev
> tsnd --respawn -r tsconfig-paths/register src/startup/index.ts

Debugger listening on ws://127.0.0.1:60158/3b1fa96a-a992-4d8c-8b8d-b34acb4ba0b5
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[INFO] 11:49:52 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
Debugger listening on ws://127.0.0.1:60160/eae2fb76-f86e-4c15-8810-7773d696a5ae
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
---kernel
{
  APP_URL: 'http://localhost:3000',
  ROOT_URL: 'http://localhost:4000',
  ROOT_PORT: 4000,
  MONGO_URL: 'mongodb://localhost:27017/test123',
  CONTEXT: 'development',
  AWS_ACCESS_KEY_ID: 'EXOee841d69b42d8902716276e1',
  AWS_SECRET_ACCESS_KEY: 'QGqvWsXhbtu6unLWugKy4MgFLhhrxpbO_nM2Ky7UCzQ',
  AWS_BUCKET: 'dev-neumake3d',
  AWS_REGION: 'eu-west-1',
  AWS_ENDPOINT: 'https://sos-at-vie-1.exo.io'
}
[class XS3Bundle extends Bundle]

xxxxxxx      xxxxxxx
 x:::::x    x:::::x 
  x:::::x  x:::::x  
   x:::::xx:::::x   
    x::::::::::x    
     x::::::::x     X-Framework Server by BlueLibs
     x::::::::x     You are in control.
    x::::::::::x    
   x:::::xx:::::x   
  x:::::x  x:::::x  
 x:::::x    x:::::x 
xxxxxxx      xxxxxxx 

 info  Connecting to MongoDB database...
(node:96805) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
 info  Connected to the database.
(node:96805) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead 
 info  HTTP Server listening on port: 4000
 info  GraphQL endpoint ready: http://localhost:4000/graphql
 error  {
    "message": "The AWS Access Key Id you provided does not exist in our records.",
    "locations": [
        {
            "line": 2,
            "column": 3
        }
    ],
    "path": [
        "AppFileUpload"
    ],
    "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
            "message": "The AWS Access Key Id you provided does not exist in our records.",
            "code": "InvalidAccessKeyId",
            "region": null,
            "time": "2023-02-27T10:51:34.256Z",
            "requestId": "0GK844V5YZJWV2E9",
            "extendedRequestId": "YUZ/iMpzHvlbuWFV3ZPsxGmqsP6CMfXvh78ZLIpW0zys/ZCobAUSjuyhdl4ve5lSx4//082tPD18dIVgx6pUNQ==",
            "statusCode": 403,
            "retryable": false,
            "retryDelay": 53.22943752859442,
            "stacktrace": [
                "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.",
                "    at Request.extractError (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/services/s3.js:711:35)",
                "    at Request.callListeners (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
                "    at Request.emit (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
                "    at Request.emit (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:686:14)",
                "    at Request.transition (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:22:10)",
                "    at AcceptorStateMachine.runTo (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/state_machine.js:14:12)",
                "    at /Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/state_machine.js:26:10",
                "    at Request.<anonymous> (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:38:9)",
                "    at Request.<anonymous> (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/request.js:688:12)",
                "    at Request.callListeners (/Users/thomaskamsker/Documents/Atom/2023/neumake3d/microservices/api/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
            ]
        }
    }
}

when i access in admin Edit Filelibrary where i have 2 uploads relations in blueprint collection similar to 
  relations: [
    shortcuts.relation.file("modelFile", { isRequired: false }),

So it seems where was s3 is called the variables are gone

**Comment by theodorDiaconu** [comment]
This problem was related to improper check of configs. Follow the latest readme and it will work.
