### ISSUE TITLE
Smart and React 18 StrictMode

### ISSUE THREAD

**Issue by HassanHeydariNasab** [bluelibs/bluelibs#330]
**To Reproduce**
1. Setup a React.js or Next.js microservice
2. Upgrade to React v18 illegally :smiley: 
3. Create and use Smart
4. Make ReactStrictMode on/off 

**Current behavior**
When the provider is just on top of the consumer, Smart state changes delays until next component render (usual render caused by component state/props change). When the provider is higher, the changes take effect when navigation occurs (Next.js)

**Expected behavior**
It should be like when we are in React v17 or React v18 without ReactStrictMode.

**Additional context**
It seems that current implementation for Smart breaks some React hook rules.
https://react.dev/reference/react/StrictMode

**Demo**
Compare Smart (current Smart implementation) and Stupid (desired behavior)
https://github.com/HassanHeydariNasab/stupid

**Comment by theodorDiaconu** [comment]
React 18 supported all over the board now.
