### ISSUE TITLE
Ability to have a custom foreign field instead of forcing _id 

### ISSUE THREAD

**Issue by 0ctanium** [bluelibs/bluelibs#331]
**Is your feature request related to a problem? Please describe.**
When using Nova (or X) I have a secondary ID that is linked to a secondary ID. Both of those IDs are retrieved from a third-party app. Hence It's stored in a secondary ID. But I would want to make a relation between the 

**Describe the solution you'd like**
You can see in the code under '_id' is used by default. when searching for a foreign field What I think should be done, is to use the `field` in the related linker. (And using by default '_id'). 
 

It would require some change in the generation of the lookup. And the usage of "isVirtual". But would do the trick.

I think it is the best solution because from my point of view, defining the reference field in the collection itself (instead of two times in each collection) would keep the code DRY and then easier to understand in the schema.

What could also be done and that would'nt require much change in the current Linker logic, is to add a new property aside of the `field` to override the foreign field "_id".

**Comment by theodorDiaconu** [comment]
Please help me understand the context better:

> When using Nova (or X) I have a secondary ID that is linked to a secondary ID. Both of those IDs are retrieved from a third-party app. Hence It's stored in a secondary ID. But I would want to make a relation between the

What is the exact situation here?

**Comment by 0ctanium** [comment]
I've done some testing on my side and found a solution where we replace every hardcoded `_id` used when linking, to a field in the Linker that has a default value of `_id` but can still be configured.

I opened a draft PR here: https://github.com/bluelibs/bluelibs/pull/332

It will need to write some additional tests. But right now the code works.

**Comment by theodorDiaconu** [comment]
Understood the concept. This basically removes the '_id' limitation from linking collections. Be sure to update the DOCUMENTATION.md as well. This is a good use-case and makes the library better, thanks.

**Comment by theodorDiaconu** [comment]
It has been implemented.
