### ISSUE TITLE
(question) I think there is a small typo in the Blueprint documentation.

### ISSUE THREAD

**Issue by Mako-L** [bluelibs/bluelibs#334]
![Screenshot 2023-11-06 105517](https://github.com/bluelibs/bluelibs/assets/9460018/08647623-3c60-46dc-a1e8-29053aa5e198)
(https://www.bluelibs.com/docs/package-blueprint/#collections)
There is a small typo in the documentation of blueprint. Instead of `fields.types.STRING` it should be `field.types.STRING` because in current scenario `fields` is `undefined`.

**Comment by theodorDiaconu** [comment]
Check
