### ISSUE TITLE
(Nova + Meteor) Is it possible to use Nova with Meteor?

### ISSUE THREAD

**Issue by pmogollons** [bluelibs/bluelibs#338]
Im trying to use Nova with Meteor, but it looks like addReducers and addLinks dont support using ```MeteorCollection.rawCollection()```. 

While testing I saw that when creating a collection with
```js
const PostCollection = new Mongo.Collection("test_post");
```
The output is different than when using
```js
const Post = await MongoInternals.defaultRemoteCollectionDriver().mongo.db.createCollection("Post");
```

When creating a collection directly with the node driver everything works, but when creating with meteor version it doesnt work.

Any clues on what can be done to use rawCollection or something similar to use Nova inside Meteor?

**Comment by theodorDiaconu** [comment]
Interesting, I think I might know the culprit, can you try attaching links in Meteor.startup(() => { addLinks() }) function. I noticed that the references for .rawCollection() change as Meteor starts-up.

**Comment by theodorDiaconu** [comment]
I'm closing this because I'm almost sure that's the case, if not feel free to reopen and I'm happy to help to ensure it works with Meteor.
