### ISSUE TITLE
[apollo-bundle] GraphQL Middleware used at root path "/", thus overriding additional routes.

### ISSUE THREAD

**Issue by 0ctanium** [bluelibs/bluelibs#339]
**Describe the bug**
The Apollo bundle use the expressMiddleware with the path "/". And the additional routes initialized by "addRoutesToExpress" are ran after it. 
Because the graphql middleware uses the path "/". Express will always match the graphql middleware first, thus trying to execute the graphql query instead of the handler specified within the route.

**To Reproduce**
1. Init a bluelibs app using the ApolloBundle
2. Setup any custom route using the `routes` option.
3. Call said route
4. The app returns an internal server error 

**Expected behavior**
After the route is called, the handler should be executed instead of the graphql middleware.

**How to solve the problem**
```diff
--- packages/apollo-bundle/src/ApolloBundle.ts
+++ packages/apollo-bundle/src/ApolloBundle.ts
@@ -269,7 +269,7 @@ export class ApolloBundle extends Bundle<ApolloBundleConfigType> {
       await apolloServer.start();
 
       app.use(
-        "/",
+        "/graphql",
         cors<cors.CorsRequest>(),
         bodyParser.json(),
         // expressMiddleware accepts the same arguments:
```

**Comment by 0ctanium** [comment]
Also, in this case, Bluelibs does not seem to properly handle the errors that might be generated by apollo. 
Apollo server throws an error because the query does not contain a valid GraphQL query (or it might break before this because of CRSF protection)

And Bluelibs tries to handle the apollo error as a regular GraphQL error. But breaks and then throws an internal server error (without any logging, btw)

**Comment by theodorDiaconu** [comment]
@0ctanium thank you very much, makes sense. Can you please clarify "Bluelibs does not seem to properly handle the errors that might be generated by apollo." 

Are you referring to "express routes" from apollo? How are they treated as GraphQL queries?

**Comment by theodorDiaconu** [comment]
Updated to 2.0.8, awaiting your response in regards to the errors.

**Comment by Fen747** [comment]
Hey @theodorDiaconu ,
Hope you are well.
Could you describe the way you update the semver ? Unfortuntaletely, lately, our client's app has been down twice because breaking changes had been introduced as patches, resulting in automatic changes when redeploying the app that ended up braking the app
