### ISSUE TITLE
Compatibility with mongodb 5 and 6?

### ISSUE THREAD

**Issue by Floriferous** [bluelibs/bluelibs#346]
Nova pins mongodb to version 4, is there a reason why it does not support v5 or v6? Could we change it to `"mongodb": "4 - 6"`? 

Maybe we could keep track of what is required to allow higher versions of the mongodb package.

**Comment by theodorDiaconu** [comment]
There's no reason it shouldn't. We should also be aware of running tests for the mentioned versions. I wonder if there's a way, for that.

**Comment by theodorDiaconu** [comment]
@bluelibs/nova@1.7.0 
supports all mongo versions.
