### ISSUE TITLE
Static property Links does not exist on Collection

### ISSUE THREAD

**Issue by Floriferous** [bluelibs/bluelibs#347]
I'm following the docs here (https://www.bluelibs.com/docs/package-mongo#nova-integration) to add links to my collections, but I get a typescript error when I do this:

`Class static side 'typeof PostsCollection' incorrectly extends base class static side 'typeof Collection'.
  Types of property 'links' are incompatible.`

Might be a type issue, or I'm missing something?

**Comment by theodorDiaconu** [comment]
Show me the code pls

**Comment by theodorDiaconu** [comment]
@Floriferous can you show me the code it fails?
