### ISSUE TITLE
[Nova] Deeply nested reducers dont work and freeze the app running it

### ISSUE THREAD

**Issue by pmogollons** [bluelibs/bluelibs#349]
**Describe the bug**
When you have a reducer that depends another reducer that also depends another reducer the query freezes the app. Nova can support 2 reducers deep, 3 or more makes it fail.

```js
  addReducers(Deals, {
    notesLength: {
      dependency: {
        notes: true,
      },
      async reduce(deal) {
        return deal.notes?.length;
      }
    },
    hasNotes: {
      dependency: {
        notesLength: true,
      },
      async reduce(deal) {
        return deal.notesLength > 0;
      }
    },
    sureItHasNotes: {
      dependency: {
        hasNotes: true,
      },
      async reduce(deal) {
        return deal.hasNotes === true; // Edited
      }
    }
  });

  const tasks = await query(Deals, {
      _id: 1,
      name: 1,
      sureItHasNotes: 1,
  }).fetch();
```

With this reducers `notesLength` works ok, `hasNotes`works ok, but `sureItHasNotes`freezes the app running the query.

**To Reproduce**
Just add reducers like in the example and create a query that calls the deeply nested reducer.

**Expected behavior**
The query should not freeze, and should return the values of hasNotes.

**Desktop (please complete the following information):**
 - OS: OSX
 - Node 20.9

**Comment by theodorDiaconu** [comment]
I think it’s because of a failed reduce promise? It should be deal.hasNotes === true. 

but tell me how the app hangs as we should have descriptive errors everywhere

**Comment by theodorDiaconu** [comment]
@pmogollons please confirm if this has been fixed with the one above and also what does it mean to 'freeze'? It blocks the server into infinite loop?

**Comment by pmogollons** [comment]
Yes, still having the issue. The server is blocked, in some cases I cant even close the terminal as it gets completely blocked or freezed. It doesnt crash.

**Comment by theodorDiaconu** [comment]
Sorry for the delay, @bluelibs/nova@1.7.3 should be fine now with as many dependencies as you wish.
