### ISSUE TITLE
Reducer projection clashes with query projection

### ISSUE THREAD

**Issue by Floriferous** [bluelibs/bluelibs#351]
**Describe the bug**
When a reducer depends on a nested field, if you query the reducer and a larger field that includes the nested field, you get the wrong data back.

**To Reproduce**
Have a reducer like this:

```js
myReducer: {
  dependency: { nested: { field: 1 } },
  reduce: () => {},
}
```

Query your document like this:
```js
query({
  nested: 1,
  myReducer: 1,
  otherField: 1,
})
```

You get back the following:
```js
{
  nested: { field: 'a' }, // Missing all other fields inside of this nested field
  myReducer: 'b',
  otherField: 'c'
}
```

**Expected behavior**
I expect the entire `nested` field to be present, as the query should take precedence over the reducer.

**Comment by theodorDiaconu** [comment]
@bluelibs/nova@1.7.2
