### ISSUE TITLE
(x) Support default values

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#4]
**Is your feature request related to a problem? Please describe.**
When creating a collection and its cru, I expect many field to have default values, both on forms, API inputs & at database level

**Describe the solution you'd like**
Allow adding a `default` key in a field. That could be anything, we can leave to the developper the responsability to set a valid data (an empty string for a STRING field, a valid enum value, etc), or we could control it and prevent generation if it's invalid, but that seems a long shot for now.

Having default values is a must-have in any application, to avoid redundancy when inserting, limit code-size and improve predictability and consistency over the stored data

**Comment by theodorDiaconu** [comment]
Proposal:

- Arrays will always have a default value of [] unless specified
- Default value can be either a string, number, date, boolean, an array of jsonable values.
- If the field is an enum the value is the value of the `enum` itself, it will be manually put in there. And checked if it doesn't match with any of existing values.
