### ISSUE TITLE
(x) Introduce a skip, only strategy for collections.

### ISSUE THREAD

**Issue by theodorDiaconu** [bluelibs/bluelibs#43]
Introduce `skip` and `only` for collections. Sometimes as your app grows you might want to generate things only for specific set of collections, or you're playing around with one collection and you don't want it to affect other files.

**Comment by y-moufakkr** [comment]
do we want to add skip and only fields to the app in blueprint : 
```
const application = app({
  id: "ubuntu",
  sharedModels: Object.values(SharedModels),
  collections: Object.values(Collections),
skip:['Users'],
only:['Contracts']
});
```
also do we need an extra option if wanna ignore relations that we wanna skip, or ignore the skip decision,
or just throw an error if there s a relation with a collection in skip
