### ISSUE TITLE
String type enhancement

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#7]
**Is your feature request related to a problem? Please describe.**
When generating forms with STRING type field, we have no posibility to choose the input type

**Describe the solution you'd like**
For STRING type fields, add a `kind` option to the UI : "simple" | "multiline" | "rich" | "email" | "password".

This would allow the generator to choose what code to generate exactly, and could even allow the server to check for XSS code in rich text, and add some regex validation.

**Comment by theodorDiaconu** [comment]
Will get solved by the: https://github.com/bluelibs/bluelibs/issues/16
