### ISSUE TITLE
Blueprint : improve `field` function

### ISSUE THREAD

**Issue by Fen747** [bluelibs/bluelibs#78]
**Is your feature request related to a problem? Please describe.**
I face a case where I wanted a field to be a `required string`, with `""` a default value. Unfortunately, `yup` consider `""` as falsy and throws (Who said javascript's shitty ?). After a quick search, it seems that authorizing a valid empty string can be done [like this](https://stackoverflow.com/questions/63943689/how-to-get-yup-string-to-require-string-of-any-length-including-0).

I then thought : "As it's a quite particular test rule, but quite common use case too, it might be useful to have a `allowEmptyString` in `blueprint`'s `field` function". But of course, that would be messy to have it available for all type of field.

Then, I thought about something we already talked about with @theodorDiaconu : `field` should take inspiration from graphql's [`Nexus`](https://nexusjs.org/) lib.

**Describe the solution you'd like**
Have one `field` function per type. It would allow :

- better IDE autocompletion
- So much better reaadbility with less code on screen
- surely it would also be useful down the road to allow extending the possible kind of field with custom functions (url, email, address, richText, etc).

Some examples :

```typescript
// A required string, can be empty and must be less than 10 chars
field.required.string("firstname", {
    allowEmpty: true, // Consider empty string to be valid
    defaultValue: "",
    max: 10 // No more than 10 characters
})

// An optional array of floats contained between 0 and 20, with steps of 1 (for number input html "step" attribute )
field.list.float("grades", {
    min: 5,
    max: 20,
    step: 1,
})

// A custom kind of field. It should load the component from a js Map, if it exists. NPM modules could later register their own component in this Map, as well as GQL aliases / objects / inputs, etc
addressField("lastKnownPosition", {
    includeGeopoint: true
})
```

**Comment by theodorDiaconu** [comment]
We currently did this with `field.string()` the strategy of linking information can be bad design. Especially since the whole logic is to import from the utils.ts where you could configure your default behaviors, adding this will make it harder. 

```ts
field.string("id", { isRequired: false })
vs
field.optional.string("id"); // this seems harder to configure, and split. 
```

You can easily create your own custom functions like this, as you prefer
```ts
function list(data: Partial<Field>) { return field({ ...data, isArray: true }); }
```
