### ISSUE TITLE
bluelibs/x-ui events not working

### ISSUE THREAD

**Issue by AranNomante** [bluelibs/bluelibs#92]
How the handler is defined:
```
  import { listen } from "@bluelibs/x-ui";
  ......
  ......
  const handler = (e: typeof props.refetchEvent) => {
    refetch();
  }
  listen(props.refetchEvent, handler);
  ......
```
How the emitter is defined:
```
  import { useEventManager } from "@bluelibs/x-ui"; 
  ......
  ......
  const eventManager = useEventManager();
  ......
  ......
  eventManager.emit(new props.refetchEvent({ what: "refetch" }));
  ......
  ......
```

**Comment by y-moufakkr** [comment]
Hello @AranNomante , I tested the ui-events on  2 react components and its working fine, 
you might having problems with triggering the event, either you r not calling the emit, or you are calling the emit before the `.listen()` is ready, 
also props.refetchEvent should be extended from Event<T>
